<a href="https://colab.research.google.com/github/caexequiel/caexequiel/blob/main/Copia_de_Sem_02_Clase_02_Repaso_1_de_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Sem 02 - Clase 02 - Repaso 1 de 2

Esta Notebook servirá para reapaso y practica.

### Ejercicios Tipos de datos

1. Hacer una lista que contenga 3 materias de la escuela

2. Eliminar el primer registro de la lista

3. Agregar una materia más al final

4. Seleccionar el segundo elemento de la lista

5. Crear un diccionario con las materias y el nombre del/la profesor/a

6. Agregar una materia y un/a profesora/

7. Eliminar una materia y un/a profesor/a

In [ ]:
materias = ["lengua", "programacion", "ciencia"]
materias

['lengua', 'programacion', 'ciencia']

In [ ]:
del materias[0]
materias

['programacion', 'ciencia']

In [ ]:
materias.append("matemática")
materias

['programacion', 'ciencia', 'matemática']

In [ ]:
materias[2]

'matemática'

In [ ]:
diccionario = { "pepe":"lengua" , "juana":"tecnologia"}
print(diccionario)

{'pepe': 'lengua', 'juana': 'tecnologia'}

In [ ]:
diccionario.update({"mario":"dibujo"})

In [ ]:
diccionario

{'pepe': 'lengua', 'juana': 'tecnologia', 'mario': 'dibujo'}

In [ ]:
diccionario.pop("pepe")

'lengua'

In [ ]:
diccionario

{'juana': 'tecnologia', 'mario': 'dibujo'}

### Ejericicios estructuras de control

1. Definir 2 variables con números (num1 y num2). Crear una estructura condicional donde si los dos números son iguales se imprima "los dos números son iguales" (*if... else...*)

2. Crear una estructura condicional donde si "no llueve", "podemos ir a la plaza" y sino "debemos quedarnos en casa" (*if... else...*)

3. Definir una lista con 3 números (puede ser la misma que antes). Crear una estructura iterativa donde se imprima cada número +2 (*for... in...*)

4. Crear una lista con 5 materias de la escuela. Crear una estructura interativa que permita CONTAR la cantidad de elementos en la lista (*for... in...*)

5. Crea una función que divida dos números que reciba como parámetros

6. Crea una función que reciba 2 números e incluya un condicional donde si el segundo número es 0 imprima "no se puede realizar esta operación" y sino realice una división entre el primer y el segundo número.

7. Crear una función que dada una lista de números y un número (parámetros), agregue el número a la lista (*def*)

In [ ]:
num1 = 2
num2 = 3

if num1 == num2:
  print("los numeros son iguales")
else:
  print("los numeros NO son iguales")

los numeros NO son iguales

In [ ]:
# Crear una estructura condicional donde si "no llueve", "podemos ir a la plaza" y sino "debemos quedarnos en casa" (if... else...)

In [ ]:
milista = [4, 10, 18]
for i in milista:
  suma = i + 2
  print(suma)

6
12
20

In [ ]:
lista = [4, 10, 18]
for i in lista:
    print(i+2)

6
12
20

In [ ]:
materias = ["lengua", "programacion", "ciencia", "mate", "dibujo", "ed fisica"]

acumulador = 0
for i in materias:
  if i != "":
    acumulador +=1

acumulador

6

In [ ]:
num1 = int(input("ingresa primer numero"))
num2 = int(input("ingresa segundo numero"))

def dividir(numA,numB):
  return numA//numB

dividir(num1,num2)

ingresa primer numero20
ingresa segundo numero5

4

In [ ]:
def dividirNumeros(numero1,numero2):
  return numero1//numero2
dividirNumeros(10,5)

2

In [ ]:
num1 = int(input("ingresa primer numero"))
num2 = int(input("ingresa segundo numero"))

def dividir(numA,numB):
  if numB == 0:
    print("no se puede realizar esta operación")
  else:
    return numA//numB

dividir(num1,num2)

ingresa primer numero9
ingresa segundo numero0
no se puede realizar esta operación

In [ ]:
# Crear una función que dada una lista de números y un número (parámetros), agregue el número a la lista (def)

In [ ]:
# df = data

tipo_efector = data["TIPO_EFECTOR"]=="Público"
data_tipo_efector = data.loc[tipo_efector]
data_tipo_efector.head(3)

,FECHA_ADMINISTRACION,GRUPO_ETARIO,GENERO,VACUNA,TIPO_EFECTOR,DOSIS_1,DOSIS_2,ID_CARGA,DOSIS_3
1,25FEB2021:00:00:00,31 a 40,M,AstraZeneca,Público,6,0,NaN,0.0
3,25FEB2021:00:00:00,31 a 40,M,Sputnik,Público,230,76,NaN,0.0
5,25FEB2021:00:00:00,41 a 50,F,AstraZeneca,Público,16,0,NaN,0.0

### Ejercicios Dataset pandas

Para estos ejercicios utilizaremos un dataset extraído de https://data.buenosaires.gob.ar/dataset/plan-de-vacunacion-covid-19 con la información de las vacunas dadas en la Ciudad de Buenos Aires entre el 8/3/2021 hasta el 31/01/22

#### Preparo el Entorno de trabajo

In [ ]:
import pandas as pd

In [ ]:
# Este metodo es para bajar los datos de la Web. Importante: Hay que contar con la URL.
data = pd.read_csv("https://cdn.buenosaires.gob.ar/datosabiertos/datasets/ministerio-de-salud/plan-de-vacunacion-covid-19/dataset_total_vacunas.csv")

In [ ]:
#data.head(5)   miro cabecera y 5 filas los datos
data     # miro "todos" los datos

,FECHA_ADMINISTRACION,GRUPO_ETARIO,GENERO,VACUNA,TIPO_EFECTOR,DOSIS_1,DOSIS_2,ID_CARGA,DOSIS_3
0,07FEB2021:00:00:00,41 a 50,F,Sputnik,Privado,13,16,NaN,0.0
1,07FEB2021:00:00:00,41 a 50,F,Sputnik,Público,54,107,NaN,0.0
2,07FEB2021:00:00:00,41 a 50,F,Sputnik,Público nacional,0,2,NaN,0.0
3,07FEB2021:00:00:00,41 a 50,M,Sputnik,Privado,7,15,NaN,0.0
4,07FEB2021:00:00:00,41 a 50,M,Sputnik,Público,28,56,NaN,0.0
...,...,...,...,...,...,...,...,...,...
48834,21MAR2023:00:00:00,71 a 80,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,NaN,1.0
48835,21MAR2023:00:00:00,81 a 90,F,Moderna,Público,0,0,NaN,0.0
48836,21MAR2023:00:00:00,81 a 90,F,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,NaN,0.0
48837,21MAR2023:00:00:00,81 a 90,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,NaN,0.0
48838,21MAR2023:00:00:00,91 o mas,F,Moderna,Público,0,0,NaN,0.0

#### Ejercicios pandas 1: exploración

1. Ver las 3 útlimas filas del dataset.

2. Ver el tamaño del dataset

2. Ver los nombres de las columnas

3. Seleccionar la columna "TIPO_EFECTOR". Ver que valores toma esa columna y cuántos registros hay de cada uno.

3. ¿Cuál es el registro en el que se dieron mayor cantidad de vacunas de DOSIS_1? ¿Cuántas vacunas se dieron? ¿Y de DOSIS_2?

4. Eliminar la columna "ID_CARGA

5. Cambiar los nombres de todas las columnas a minuscula

In [ ]:
data.tail(10)   # con tail miro  desde abajo hacia arriba las instancias el parametro es 5

,FECHA_ADMINISTRACION,GRUPO_ETARIO,GENERO,VACUNA,TIPO_EFECTOR,DOSIS_1,DOSIS_2,ID_CARGA,DOSIS_3
48829,21MAR2023:00:00:00,61 a 70,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,1,NaN,1.0
48830,21MAR2023:00:00:00,71 a 80,F,Moderna,Público,0,0,NaN,0.0
48831,21MAR2023:00:00:00,71 a 80,F,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,NaN,0.0
48832,21MAR2023:00:00:00,71 a 80,M,Moderna,Público,0,0,NaN,0.0
48833,21MAR2023:00:00:00,71 a 80,M,Sinopharm,Público,0,1,NaN,1.0
48834,21MAR2023:00:00:00,71 a 80,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,NaN,1.0
48835,21MAR2023:00:00:00,81 a 90,F,Moderna,Público,0,0,NaN,0.0
48836,21MAR2023:00:00:00,81 a 90,F,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,NaN,0.0
48837,21MAR2023:00:00:00,81 a 90,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,NaN,0.0
48838,21MAR2023:00:00:00,91 o mas,F,Moderna,Público,0,0,NaN,0.0

In [ ]:
# tamaño del dataset
data.size

439551

In [ ]:
# nombres de las columnas
data.columns

Index(['FECHA_ADMINISTRACION', 'GRUPO_ETARIO', 'GENERO', 'VACUNA',
       'TIPO_EFECTOR', 'DOSIS_1', 'DOSIS_2', 'DOSIS_3'],
      dtype='object')

In [ ]:
 #Seleccionar la columna "TIPO_EFECTOR". Ver que valores toma esa columna y cuántos registros hay de cada uno.
 data['TIPO_EFECTOR'].info()    # esta da información general
 data['TIPO_EFECTOR'].value_counts()  # esta función devuelve frecuencia absoluta de cada valor

<class 'pandas.core.series.Series'>
RangeIndex: 48839 entries, 0 to 48838
Series name: TIPO_EFECTOR
Non-Null Count  Dtype
--------------  -----
48839 non-null  object
dtypes: object(1)
memory usage: 381.7+ KB

Público             40247
Privado              6369
Público nacional     2223
Name: TIPO_EFECTOR, dtype: int64

In [ ]:
# cual es el registro en el que se dieron mayor cantidad de vacunas de DOSIS_1? ¿Cuántas vacunas se dieron? ¿Y de DOSIS_2?
data["DOSIS_1"].describe()    # esta devuelve información general y me dice el valor máximo pero no dice donde lo encuentra
print (data)
data['DOSIS_1'].idxmax()

data.iloc[17426]
data.iloc [data['DOSIS_1'].idxmax()]

      FECHA_ADMINISTRACION GRUPO_ETARIO GENERO  \
0       07FEB2021:00:00:00      41 a 50      F
1       07FEB2021:00:00:00      41 a 50      F
2       07FEB2021:00:00:00      41 a 50      F
3       07FEB2021:00:00:00      41 a 50      M
4       07FEB2021:00:00:00      41 a 50      M
...                    ...          ...    ...
48834   21MAR2023:00:00:00      71 a 80      M
48835   21MAR2023:00:00:00      81 a 90      F
48836   21MAR2023:00:00:00      81 a 90      F
48837   21MAR2023:00:00:00      81 a 90      M
48838   21MAR2023:00:00:00     91 o mas      F

                                                  VACUNA      TIPO_EFECTOR  \
0                                                Sputnik           Privado
1                                                Sputnik           Público
2                                                Sputnik  Público nacional
3                                                Sputnik           Privado
4                                                Sputnik           Público
...                                                  ...               ...
48834  vacuna Coronavirus (PFIZER) Bivalente, vial x ...           Público
48835                                            Moderna           Público
48836  vacuna Coronavirus (PFIZER) Bivalente, vial x ...           Público
48837  vacuna Coronavirus (PFIZER) Bivalente, vial x ...           Público
48838                                            Moderna           Público

       DOSIS_1  DOSIS_2  ID_CARGA  DOSIS_3
0           13       16       NaN      0.0
1           54      107       NaN      0.0
2            0        2       NaN      0.0
3            7       15       NaN      0.0
4           28       56       NaN      0.0
...        ...      ...       ...      ...
48834        0        0       NaN      1.0
48835        0        0       NaN      0.0
48836        0        0       NaN      0.0
48837        0        0       NaN      0.0
48838        0        0       NaN      0.0

[48839 rows x 9 columns]

FECHA_ADMINISTRACION    28JUL2021:00:00:00
GRUPO_ETARIO                    30 o menos
GENERO                                   F
VACUNA                           Sinopharm
TIPO_EFECTOR                       Público
DOSIS_1                              16523
DOSIS_2                                 23
ID_CARGA                               NaN
DOSIS_3                                0.0
Name: 17426, dtype: object

In [ ]:
# eliminamos columna    si ya lo borré no me deja ejecutar  nuevamente la sentencia de borrado

del(data['ID_CARGA'])

KeyError: ignored

In [ ]:
#cambiamos a minusculas
data.rename(columns=str.lower)

,fecha_administracion,grupo_etario,genero,vacuna,tipo_efector,dosis_1,dosis_2,dosis_3
0,07FEB2021:00:00:00,41 a 50,F,Sputnik,Privado,13,16,0.0
1,07FEB2021:00:00:00,41 a 50,F,Sputnik,Público,54,107,0.0
2,07FEB2021:00:00:00,41 a 50,F,Sputnik,Público nacional,0,2,0.0
3,07FEB2021:00:00:00,41 a 50,M,Sputnik,Privado,7,15,0.0
4,07FEB2021:00:00:00,41 a 50,M,Sputnik,Público,28,56,0.0
...,...,...,...,...,...,...,...,...
48834,21MAR2023:00:00:00,71 a 80,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,1.0
48835,21MAR2023:00:00:00,81 a 90,F,Moderna,Público,0,0,0.0
48836,21MAR2023:00:00:00,81 a 90,F,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,0.0
48837,21MAR2023:00:00:00,81 a 90,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,0.0
48838,21MAR2023:00:00:00,91 o mas,F,Moderna,Público,0,0,0.0

In [ ]:
# ver el registro que tiene  los 16523 personas
data.iloc[17426]

FECHA_ADMINISTRACION    28JUL2021:00:00:00
GRUPO_ETARIO                    30 o menos
GENERO                                   F
VACUNA                           Sinopharm
TIPO_EFECTOR                       Público
DOSIS_1                              16523
DOSIS_2                                 23
DOSIS_3                                0.0
Name: 17426, dtype: object

In [ ]:
data=data.rename(columns=str.lower)
data

,fecha_administracion,grupo_etario,genero,vacuna,tipo_efector,dosis_1,dosis_2,dosis_3
0,07FEB2021:00:00:00,41 a 50,F,Sputnik,Privado,13,16,0.0
1,07FEB2021:00:00:00,41 a 50,F,Sputnik,Público,54,107,0.0
2,07FEB2021:00:00:00,41 a 50,F,Sputnik,Público nacional,0,2,0.0
3,07FEB2021:00:00:00,41 a 50,M,Sputnik,Privado,7,15,0.0
4,07FEB2021:00:00:00,41 a 50,M,Sputnik,Público,28,56,0.0
...,...,...,...,...,...,...,...,...
48834,21MAR2023:00:00:00,71 a 80,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,1.0
48835,21MAR2023:00:00:00,81 a 90,F,Moderna,Público,0,0,0.0
48836,21MAR2023:00:00:00,81 a 90,F,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,0.0
48837,21MAR2023:00:00:00,81 a 90,M,"vacuna Coronavirus (PFIZER) Bivalente, vial x ...",Público,0,0,0.0
48838,21MAR2023:00:00:00,91 o mas,F,Moderna,Público,0,0,0.0

#### Ejercicios pandas 2: filtrar y agrupar

Filtrar

1. Crear un nuevo Dataframe solamente con las vacunas aplicadas en Efectores Públicos.

2. Crear un nuevo Dataframe solamente con las vacunas aplicadas a personas de entre 41 a 50 años.

3. Calcular cuántas vacunas DOSIS_1 "Sinopharm" se dieron en efectores Públicos. Hacer con dos filtros, debe usarse el signo "&" y colocar cada uno entre parentesis: [(filtro1) & (filtro2)]

4. Calcular cuántas vacunas "Sputnik" DOSIS_2 se dieron a mujeres.

In [ ]:
grupo_etario = data["GRUPO_ETARIO"]=="41 a 50"
data_grupo_etario = data.loc[grupo_etario]
data_grupo_etario.head(3)

,FECHA_ADMINISTRACION,GRUPO_ETARIO,GENERO,VACUNA,TIPO_EFECTOR,DOSIS_1,DOSIS_2,ID_CARGA,DOSIS_3
5,25FEB2021:00:00:00,41 a 50,F,AstraZeneca,Público,16,0,NaN,0.0
6,25FEB2021:00:00:00,41 a 50,F,Sputnik,Privado,230,14,NaN,0.0
7,25FEB2021:00:00:00,41 a 50,F,Sputnik,Público,362,241,NaN,0.0

In [ ]:
vacuna = data["VACUNA"]=="Sinopharm"
tipo_efector = data["TIPO_EFECTOR"]=="Público"

data_vacuna_t_efector = data.loc[(vacuna)&(tipo_efector)]

data_vacuna_t_efector["DOSIS_1"].sum()

987586

In [ ]:
vacuna = data["VACUNA"]=="Sputnik"
genero = data["GENERO"]=="F"

data_vacuna_genero = data.loc[(vacuna)&(genero)]

data_vacuna_genero["DOSIS_2"].sum()

352480

Agrupar

5. Generar un Dataframe con la cantidad de vacunas DOSIS_1 que se dieron para mujeres y para para hombres. Usar groupby.

6. Generar un Dataframe que tenga la cantidad de vacunas DOSIS_1 aplicadas a mujeres y hombres de cada tipo de vacuna. Usar groupby.

7. Calcular cuántas vacunas de DOSIS_1 y cuantas vacunas de DOSIS_2 se dieron en cada efector, y en total (sumadas las dos).

In [ ]:
data.head(3)
data["GENERO"].value_counts()

F    19954
M    18549
N       51
Name: GENERO, dtype: int64

In [ ]:
#5
data_5 = data.groupby(["GENERO"])[["DOSIS_1"]].sum()
data_genero

        DOSIS_1
GENERO
F       1554043
M       1348160
N            19

In [ ]:
#6
data_6 = data.groupby(["GENERO","VACUNA"])[["DOSIS_1"]].sum()
data_genero

                                                           DOSIS_1
GENERO VACUNA
F      AstraZeneca                                          398870
       Moderna                                               15159
       Sinopharm                                            525642
       Sputnik                                              502008
       vacuna Coronavirus (CANSINO), vial x 1 dosis          14260
       vacuna Coronavirus (PFIZER) 1ra - 2da dosis, vi...    96732
       vacuna Coronavirus (PFIZER) pediátrica, vial x ...     1372
M      AstraZeneca                                          354608
       Moderna                                               18735
       Sinopharm                                            476231
       Sputnik                                              385457
       vacuna Coronavirus (CANSINO), vial x 1 dosis          15183
       vacuna Coronavirus (PFIZER) 1ra - 2da dosis, vi...    96550
       vacuna Coronavirus (PFIZER) pediátrica, vial x ...     1396
N      AstraZeneca                                               3
       Moderna                                                   0
       Sinopharm                                                14
       vacuna Coronavirus (CANSINO), vial x 1 dosis              1
       vacuna Coronavirus (PFIZER) 1ra - 2da dosis, vi...        1

In [ ]:
#7
#Dosis1
data_7_1 = data.groupby(["TIPO_EFECTOR"])[["DOSIS_1"]].sum()
data_genero



#Calcular cuántas vacunas de DOSIS_1 y cuantas vacunas de DOSIS_2 se dieron en cada efector,
#y en total (sumadas las dos).

                  DOSIS_1
TIPO_EFECTOR
Privado             98426
Público           2790583
Público nacional    13213

In [ ]:
data_7_2 = data.groupby(["TIPO_EFECTOR"])[["DOSIS_2"]].sum()
data_genero

                  DOSIS_2
TIPO_EFECTOR
Privado             64459
Público           2718221
Público nacional     7265

In [ ]:
data_7_1y2 = data.groupby(["TIPO_EFECTOR"])[["DOSIS_1", "DOSIS_2"]].sum()
data_genero

                  DOSIS_1  DOSIS_2
TIPO_EFECTOR
Privado             98426    64459
Público           2790583  2718221
Público nacional    13213     7265